directory:      ~/music/albums
library:        ~/music/library.blb
plugins:        scrub zero discogs
original_date:  yes
threaded:       no
paths:
    default:    $albumartist - $album ($year)/$track - $title
    comp:       $albumartist - $album ($year)/$track - $artist - $title
    singleton:  Singletons/$artist - $title
import:
    detail:     yes
    timid:      yes
    move:       yes
zero:
    fields:     artist_sort artist_credit albumartist_sort albumartist_credit grouping month day lyrics comments bpm comp mb_trackid mb_albumid mb_artistid mb_albumartistid albumtype label acoustid_fingerprint acoustid_id mb_releasegroupid asin catalognum script language country albumstatus media albumdisambig disctitle encoder original_year original_month original_day length bitrate format samplerate bitdepth channels
